### ISSUE TITLE
글로벌 스타일 설정

### ISSUE THREAD

**Issue by hmy751** [hmy751/inter-persona#6]
- 글로벌 스타일 설정 
  - @repo/ui에 글로벌 스타일 설정

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Removed the Chakra UI theme from apps/frontend/src/styles/theme.ts and set up global styles in a new file packages/ui/src/global.css

You can review changes in this commit: https://github.com/jjyutm4532/hmy751-inter-persona-6/commit/f8a7868706eff9132a751802e0b8b96e86e8fcae.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
